server:
  port: 8090

spring:
  application:
    name: "loans"

  profiles:
    active: "prod"

  datasource:
    #url: jdbc:h2:mem:testdb
    #driverClassName: org.h2.Driver
    #username: sa
    #password: ''
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root

  #h2:
   # console:
    #  enabled: true

  jpa:
    show-sql: true
    #database-platform: org.hibernate.dialect.H2Dialect
    #hibernate:
    #  ddl-auto: update

  sql:
    init:
      mode: always

  config:
  #  import:
  #   - "application_qa_bkp.yml"
  #   - "application_prod_bkp.yml"
     import: "optional:configserver:http://localhost:8071/"

  #rabbitmq:
    #host: "localhost"
    #port: 5672
    #username: "guest"
    #password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "loans"
    description: "Eazy Bank Loans Application"
    version: "1.0.0"

logging: # Tell Springboot framework to print DEBUG loggers present inside the package com.sauravdaruka.gatewayserver
  level:
    com:
      sauravdaruka:
        loans: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

#build:
#  version: "3.0"

#loans:
#  message: "Welcome to EazyBank loans related local APIs "
#  contactDetails:
#    name: "Amaal Grega - Developer"
#    email: "amaal@eazybank.com"
#  onCallSupport:
#    - (452) 456-2176
#    - (546) 764-8934