spring:
  application:
    name: "configserver"

  profiles:
    # active: native # when classpath is used to store the configuration
    active: git

  cloud:
    config:
      server:
        # native:
        # search-locations: "classpath:/config"
        # search-locations: "file:///Users//eazybytes//Documents//config"
        git:
          uri: "https://github.com/eazybytes/eazybytes-config.git"
          default-label: main  # default branch config server has to connect
          timeout: 5           # if connection to Github is not established, config server will wait for 5 sec before throwing error
          clone-on-start: true # clone the GitHub repo into local system during the startup itself
          force-pull: true

  #rabbitmq:
    #host: "localhost"
    #port: 5672
    #username: "guest"
    #password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

encrypt:  # This property exposes /encrypt and /decrypt endpoints
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

